version: "3.8"
services:
  frontend:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # mount your custom nginx.conf over the default vhost.
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # mount the directory holding your self-signed cert+key
      - ./ssl:/etc/nginx/ssl:ro
